name: CI - For building Jar Artifact & Publishing Release

on:
    push:
        branches: [ 'master', 'MW-2-devops' ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        
        steps:
            - uses: actions/checkout@v4

            - name: Setup JDK 8
              uses: actions/setup-java@v4
              with:
                java-version: 8
                distribution: temurin

            - name: Build JAR Artifact
              run: ./gradlew build