name: CI - For building Jar Artifact & Publishing Release

on:
    push:
        branches: [ 'master', 'MW-2-devops' ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4

            - name: Setup JDK 8
              uses: actions/setup-java@v4
              with:
                java-version: 8
                distribution: temurin

            - name: Build JAR Artifact
              run: ./gradlew build

            - name: Upload JAR Artifact
              uses: actions/upload-artifact@v4
              with:
                name: mwe-jar
                path: build/libs/*
    
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: build
        steps:
            - uses: actions/download-artifact@v4
              id: download-jar
              with:
                name: mwe-jar
            - uses: ncipollo/release-action@v1
              with:
                tag: 4.0.2-test
                artifacts: ${{ steps.download-jar.outputs.download-path }}

